version: "3.8"

services:
    backend-app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: backend-app
        restart: always
        ports:
            - 8888:8888
        networks:
            - db_net
    backend-mongo:
        image: mongo:latest
        container_name: backend-mongo
        hostname: backend-mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
        ports:
            - "0.0.0.0:27017:27017"
        networks:
            - db_net
        volumes:
            - "./mongo_data/db:/data/db"
            - "./mongo_data/configdb:/data/configdb"
    backend-mongo-express:
        image: mongo-express:latest
        container_name: backend-mongo-express
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin
            ME_CONFIG_MONGODB_SERVER: backend-mongo
            ME_CONFIG_MONGODB_PORT: "27017"
        ports:
            - "0.0.0.0:8081:8081"
        networks:
            - db_net
        depends_on:
            - backend-mongo
    backend-mysql:
        image: mysql:latest
        container_name: backend-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_DATABASE: portfolio
        ports:
            - "3306:3306"
        networks:
            - db_net
        volumes:
            - "./mysql_data:/var/lib/mysql"
networks:
    db_net:
        name: db_net
        external: true
