definitions:
  common.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  model.User:
    properties:
      createdAt:
        description: 創建時間
        type: string
      email:
        description: 電子信箱
        type: string
      enable:
        description: 帳號是否註銷
        type: integer
      headerImg:
        description: 用户头像
        type: string
      id:
        description: 主鍵ID
        type: integer
      nickName:
        description: 用户昵称
        type: string
      phone:
        description: 手機號碼
        type: string
      updatedAt:
        description: 更新時間
        type: string
      userName:
        description: 用户登录名
        type: string
      uuid:
        description: 用户UUID
        type: string
    type: object
  request.Login:
    properties:
      captcha:
        description: 驗證碼
        type: string
      password:
        description: 密碼
        type: string
      username:
        description: 帳號
        type: string
    required:
    - captcha
    - password
    - username
    type: object
  response.LoginResponse:
    properties:
      expiresAt:
        type: integer
      token:
        type: string
      user:
        $ref: '#/definitions/model.User'
    type: object
info:
  contact: {}
  description: 使用golang gin開發全端個人作品集網站
  title: E-Portfolio Swagger API接口文件
  version: v1.0.0
paths:
  /v1/auth/login:
    post:
      parameters:
      - description: 用户名, 密码, 验证码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Login'
      produces:
      - application/json
      responses:
        "200":
          description: 返回包括用户信息,token,过期时间
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.LoginResponse'
                msg:
                  type: string
              type: object
      summary: 會員登入
      tags:
      - Base
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
